#!/usr/bin/env bash
#
#  Copyright ©2020 efikarl, https://efikarl.com.
#
#  This program is just made available under the terms and conditions of the
#  MIT license: https://efikarl.com/mit-license.html.
#
#  THE PROGRAM IS DISTRIBUTED UNDER THE MIT LICENSE ON AN "AS IS" BASIS,
#  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.

THE_CMD=${BASH_SOURCE:-$0}
CMD_DIR=$( dirname ${THE_CMD})
CMD_EXE=$(basename ${THE_CMD})
# 1. try to run project stardard tool
if [[ -d $WORKSPACE ]] && [[ -e $EDK_TOOLS_PATH/Source/C ]]
then
  exec $EDK_TOOLS_PATH/Source/C/bin/$CMD_EXE $@
# 2. try to run tool in system path
elif ( command -v $CMD_EXE >/dev/null 2>&1 )
then
  exec $CMD_EXE $@
else
  echo "[ERR]:${BASH_SOURCE:-$0}: unable to find $CMD_EXE to run."
  exit 127
fi
