# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
# Triggers the workflow on push or pull request events for the master and devel branch
on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build OVMF for arch IA32
      run: docker run --rm -v ${PWD}:/ws efikarl/ovmf.build -a IA32

    - name: Upload OVMF.fd for arch IA32
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: OVMF.IA32.FD
        path: Build/OvmfIa32/DEBUG_GCC*/FV/OVMF.fd

    - name: Build OVMF for arch X64
      run: docker run --rm -v ${PWD}:/ws efikarl/ovmf.build -a X64

    - name: Upload OVMF.fd for arch X64
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: OVMF.X64.FD
        path: Build/OvmfX64/DEBUG_GCC*/FV/OVMF.fd

    - name: Build OVMF for arch IA32 X64
      run: docker run --rm -v ${PWD}:/ws efikarl/ovmf.build -a IA32 -a X64

    - name: Upload OVMF.FD for arch IA32 X64
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: OVMF.3264.FD
        path: Build/Ovmf3264/DEBUG_GCC*/FV/OVMF.fd
